AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  VideoS3Bucket:
    Type: String
    Default: placeholder

Globals:
  Function:
    Runtime: python3.12
    Timeout: 300
    MemorySize: 256
    Environment:
      Variables:
        SSM_PREFIX: /workflow-lang-automation

Resources:

  # 일정 등록: GitHub Issue → EventBridge Rules 동적 생성
  ScheduleRegisterFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: workflow-lang-schedule-register
      CodeUri: functions/schedule_register/
      Handler: app.lambda_handler
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - events:PutRule
                - events:PutTargets
                - events:DeleteRule
                - events:RemoveTargets
              Resource: "*"
            - Effect: Allow
              Action: lambda:AddPermission
              Resource: "*"

  # 알림: Slack + Telegram
  NotifyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: workflow-lang-notify
      CodeUri: functions/notify/
      Handler: app.lambda_handler
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: workflow-lang-automation/*

  # 설문조사: Google Forms 생성 + Sheets 집계
  SurveyFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: workflow-lang-survey
      CodeUri: functions/survey/
      Handler: app.lambda_handler
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: workflow-lang-automation/*

  # 미팅: Zoom 링크 생성 + Gmail 발송
  MeetingFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: workflow-lang-meeting
      CodeUri: functions/meeting/
      Handler: app.lambda_handler
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: workflow-lang-automation/*

  # 유튜브: S3 영상 → YouTube 업로드
  YoutubeFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: workflow-lang-youtube
      CodeUri: functions/youtube/
      Handler: app.lambda_handler
      Timeout: 900
      MemorySize: 1024
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: workflow-lang-automation/*
        - S3ReadPolicy:
            BucketName: !Ref VideoS3Bucket
